name: Thunderstore Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
          
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v1.7.2
    - name: Build
      run: dotnet build . --configuration Release /p:PackageOutputPath=../ReleaseOutput /p:OutputPath=../ReleaseOutput

    - name: Install TCLI
      run: dotnet tool install --global tcli

    - name: Build the mod zip file
      run: tcli build --config-path ./thunderstore.toml

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: build/*.zip
        file_glob: true
